// Englische Fassung der Wörter und Texte aus themes/standard.js - dieselben Schlüssel, gewählt über lib/i18n (getLang).
export const wordsEn = {
  group: 'Family',
  theGroup: 'the family',
  TheGroup: 'The family',
  thisGroup: 'this family',
  inGroup: 'in the family',
  ofGroup: 'of the family',
  ofAGroup: 'of a family',
  yourGroup: 'your family',
  yourGroupDat: 'your family',
  ourGroup: 'Our family',
  ownGroup: 'a family of your own',
  newGroup: 'New family',
  createGroup: 'Create family',
  createOwnGroup: 'Create your own family',
  groupName: 'Family name',
  newGroupName: 'New name',
  groupNamePlaceholder: 'e.g. Hillside family',
  groupPassword: 'Family password',
  groupSettings: 'Manage family',
  groupsDative: 'families',
  groups: 'Families',
  noGroupConnected: 'No family connected yet.',
  leaveGroup: 'Leave family',
  dissolveGroup: 'Dissolve family',
  wholeGroup: 'the whole family',
  ofThisGroup: 'of this family',
  groupNeverPublic: 'A family is never public.',
  roleGast: 'Guest',
  roleMitglied: 'Member',
  roleStellvertretung: 'Deputy',
  roleLeitung: 'Family lead',
  newsTitle: 'New in the family',
  animal: 'Animal',
  animals: 'Animals',
  thisAnimalDat: 'this animal',
  treeLabel: 'Family tree',
  toTree: 'To the animals',
  inTree: 'in the family tree',
  inTreeArticle: 'in the',
  yourTreeAcc: 'your family tree',
  treeEmpty: 'Your family tree is still empty',
  treeFit: 'Show whole family tree',
  treeView: 'Family tree view',
  littersLabel: 'Little ones',
  litter: 'Litter',
  litterBirthday: 'Siblings’ birthday',
  litterMeeting: 'Sibling meetup',
  young: 'Little ones',
  youngStage: 'Tiny',
  mating: 'Mating',
  matings: 'Matings',
  matingOf: 'of the mating',
  entry: 'Memory',
  entries: 'Memories',
  entriesDat: 'memories',
  newEntry: 'New memory',
  tellAction: 'Capture a memory',
  tellActionShort: 'Capture',
  entriesEmpty: 'No memories yet – capture the first one.',
  greeting: 'Greeting',
  greetings: 'Greetings',
  greetingAction: 'Send a greeting',
  greetingsEmpty: 'No greetings yet',
  addMating: 'Add mating',
  matingAdded: 'Mating added',
  breedingBook: 'Matings'
}

export const textsEn = {
  overviewLede:
    'So we know what the others are up to: tap an animal and see how it is doing – or tell us what it is experiencing right now.',
  overviewLedeReadOnly: 'So we know what the others are up to: tap an animal and see how it is doing.',
  feedEmpty: 'Tap an animal and tell us what it is up to',
  littersLede:
    'Siblings with the same parents and the same birthday: what they are up to now and how they looked at the same age. Built automatically from the family tree – nothing to enter.',
  littersEmpty:
    'No little ones yet: as soon as the family tree has siblings with the same parents and the same birthday, they appear here.',
  littersSingles: 'These animals have no siblings in the family tree yet.',
  plannedDue: 'The little ones should be here by now – time for new cards in the family tree!',
  breedingIntro: 'For those planning a litter: a mating appears above as expected little ones and later with the young animals.',
  matingNotesPlaceholder: 'Number of young, special notes, ultrasound …',
  loginDemoHint: 'No sign-in needed, view only – with example animals, families and memories.'
}
